# -*- coding: utf-8 -*-
{
    'name': 'Rounak Customer Portal',
    'summary': 'Customer-facing portal for Rounak Computers: dashboard, quotes, '
               'orders, invoices, subscriptions, support, payments, notifications.',
    'version': '17.0.1.0.0',
    'category': 'Website',
    'license': 'LGPL-3',
    'author': 'Rounak Computers',
    'website': 'https://www.rounakcomputers.com',
    'depends': [
        'base',
        'web',
        'portal',
        'website',
        'website_sale',
        'sale',
        'sale_management',
        'account',
        'im_livechat',
        'rounak_erp',
        'adigielite_it_service',
        'sh_all_in_one_helpdesk',
        'sh_all_in_one_website_helpdesk',
        'subscription_package',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/rounak_portal_rules.xml',
        'data/livechat_channels.xml',
        'views/portal_layout.xml',
        'views/portal_dashboard.xml',
        'views/portal_quotations.xml',
        'views/portal_orders.xml',
        'views/portal_invoices.xml',
        'views/portal_subscriptions.xml',
        'views/portal_payments.xml',
        'views/portal_support.xml',
        'views/portal_security.xml',
        'views/portal_settings.xml',
        'views/portal_notifications.xml',
        'views/portal_cart.xml',
        'views/portal_blocked.xml',
    ],
    'demo': [
        'data/portal_demo_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'rounak_portal/static/src/scss/portal_layout.scss',
            'rounak_portal/static/src/scss/portal_dashboard.scss',
            'rounak_portal/static/src/scss/portal_pages.scss',
            'rounak_portal/static/src/scss/portal_livechat.scss',
            'rounak_portal/static/src/js/portal_sidebar.js',
            'rounak_portal/static/src/js/portal_dashboard.js',
            'rounak_portal/static/src/js/portal_livechat_router.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
